// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MnnavController from "./mnnav_controller"
application.register("mnnav", MnnavController)

import SbnavController from "./sbnav_controller"
application.register("sbnav", SbnavController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)
